version: '3.8'

services:
  authelia:
    container_name: 'authelia'
    image: 'authelia/authelia'
    restart: 'unless-stopped'
    ports:
      - "9091:9091"
    networks:
      - digantara
    volumes:
      - './config:/config'
    environment:
      TZ: 'Asia/Kolkata'

networks:
  digantara:
    external: true
